server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1000MB
      max-file-size: 1000MB
      max-request-size: 1000MB
  datasource:
    #password: postgres
    #url: jdbc:postgresql://localhost:5432/advend
    #username: postgres
    url: jdbc:postgresql://ec2-52-30-67-143.eu-west-1.compute.amazonaws.com:5432/d6bt4sd5ojl5gt
    username: ofivrsfmqhsrkl
    password: 79fe40c85a3c24cd455e257e124f9232c6509243f23d588a438f5557c3015059
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
file:
  upload-dir: ./challenges/